src/Entity/Tarea.php
<?php

namespace App\Entity;

use App\Repository\TareaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TareaRepository::class)
 */
class Tarea
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $usuario_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $estado_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titulo;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Usuario::class, inversedBy="tareas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Usuario;

    /**
     * @ORM\ManyToOne(targetEntity=EstadoTarea::class, inversedBy="tareas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Estado;

    /**
     * @ORM\OneToMany(targetEntity=TareaHistorial::class, mappedBy="Tarea")
     */
    private $tareaHistorials;

    public function __construct()
    {
        $this->tareaHistorials = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsuarioId(): ?int
    {
        return $this->usuario_id;
    }

    public function setUsuarioId(int $usuario_id): self
    {
        $this->usuario_id = $usuario_id;

        return $this;
    }

    public function getEstadoId(): ?int
    {
        return $this->estado_id;
    }

    public function setEstadoId(int $estado_id): self
    {
        $this->estado_id = $estado_id;

        return $this;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUsuario(): ?Usuario
    {
        return $this->Usuario;
    }

    public function setUsuario(?Usuario $Usuario): self
    {
        $this->Usuario = $Usuario;

        return $this;
    }

    public function getEstado(): ?EstadoTarea
    {
        return $this->Estado;
    }

    public function setEstado(?EstadoTarea $Estado): self
    {
        $this->Estado = $Estado;

        return $this;
    }

    /**
     * @return Collection|TareaHistorial[]
     */
    public function getTareaHistorials(): Collection
    {
        return $this->tareaHistorials;
    }

    public function addTareaHistorial(TareaHistorial $tareaHistorial): self
    {
        if (!$this->tareaHistorials->contains($tareaHistorial)) {
            $this->tareaHistorials[] = $tareaHistorial;
            $tareaHistorial->setTarea($this);
        }

        return $this;
    }

    public function removeTareaHistorial(TareaHistorial $tareaHistorial): self
    {
        if ($this->tareaHistorials->removeElement($tareaHistorial)) {
            // set the owning side to null (unless already changed)
            if ($tareaHistorial->getTarea() === $this) {
                $tareaHistorial->setTarea(null);
            }
        }

        return $this;
    }
}

src/Form/TareaType.php
<?php

namespace App\Form;

use App\Entity\Tarea;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Validator\Constraints\NotNull;

class TareaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('usuario_id', IntegerType::class, [
                'constraints' => [
                    new NotNull(['message' => 'Usuario requerido'])
                ]
            ])
            ->add('estado_id', IntegerType::class, [
                'constraints' => [
                    new NotNull(['message' => 'Estado requerido'])
                ]
            ])
            ->add('titulo', TextType::class, [
                'constraints' => [
                    new NotNull(['message' => 'Titulo requerida'])
                ]
            ])
            ->add('description', TextType::class, [
                'constraints' => [
                    new NotNull(['message' => 'Descripcion requerida'])
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tarea::class,
            'csrf_protection' => false
        ]);
    }
}

src/Controller/TareaController.php
<?php

namespace App\Controller;

use App\Entity\EstadoTarea;
use App\Entity\Tarea;
use App\Entity\TareaHistorial;
use App\Form\TareaType;
use App\Repository\TareaRepository;
use App\Repository\EstadoTareaRepository;
use App\Repository\UsuarioRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/api")
 */
class TareaController extends AbstractApiController
{



    function __construct(
        UsuarioRepository $usuarioRepository,
        EstadoTareaRepository $estadoTareaRepository,
        TareaRepository $tareaRepository
    ) {
        $this->usuarioRepository = $usuarioRepository;
        $this->estadoTareaRepository = $estadoTareaRepository;
        $this->tareaRepository = $tareaRepository;
    }

    /**
     * @Route("/tareas", name="tarea_index", methods={"GET"})
     */
    public function index(Request $request, TareaRepository $tareaRepository): Response
    {
        $tareas =  $tareaRepository->findByUserTask($request->query->get('id'));
        return $this->json(['data' => $tareas], 200);
    }

    /**
     * @Route("/tareas", name="tarea_new", methods={"POST"})
     */
    public function new(Request $request): Response
    {
        $tarea = new Tarea();
        $historial = new TareaHistorial();
        $estado = $this->estadoTareaRepository->find($request->request->get('estado_id'));
        $usuario = $this->usuarioRepository->find($request->request->get('usuario_id'));



        $form = $this->buildForm(TareaType::class);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Tarea $tarea */
            $tarea = $form->getData();
            $tarea->setUsuario($usuario);
            $tarea->setEstado($estado);


            $historial->setEstado($estado);
            $historial->setTarea($tarea);


            $this->getDoctrine()->getManager()->persist($tarea);
            $this->getDoctrine()->getManager()->persist($historial);
            $this->getDoctrine()->getManager()->flush();

            //get Tarea 
            $response = $this->tareaRepository->getOneTask($tarea->getId());
            return $this->respond(['data' => $response]);
           

        }

        return $this->respond($form, Response::HTTP_BAD_REQUEST);
    }

    /**
     * @Route("/tareas/{id}", name="tarea_show", methods={"GET"})
     */
    public function show($id): Response
    {

         //get Tarea 
           
         $tarea = $this->tareaRepository->getOneTask($id);
        if ($tarea) return $this->respond(['data' => $tarea]);
        return $this->respond(['message' => 'Tarea inexistente'], Response::HTTP_BAD_REQUEST);
    }

    /**
     * @Route("/tareas/{id}/edit", name="tarea_edit", methods={"PUT"})
     */
    public function edit(Request $request,  $id): Response
    {
        $tarea = $this->tareaRepository->find($id);

        if (!$tarea) return $this->respond(['message' => 'Tarea inexistente'], Response::HTTP_BAD_REQUEST);


        $form = $this->buildForm(TareaType::class);
        $form->submit($request);


        if ($form->isSubmitted()) {
           
            /** @var Tarea $tarea */
            $tarea->setTitulo($request->request->get('titulo'));
            $tarea->setDescription($request->request->get('description'));
            $tarea->setUsuarioId($request->request->get('usuario_id'));
            $tarea->setEstadoId($request->request->get('estado_id'));

            $this->getDoctrine()->getManager()->flush();


            //get Tarea 
            $response = $this->tareaRepository->getOneTask($tarea->getId());
            return $this->respond(['data' => $response]);
        }
    }

    /**
     * @Route("/tareas/{id}", name="tarea_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Tarea $tarea): Response
    {

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($tarea);
        $entityManager->flush();

        return $this->respond(['data' => "tarea eliminada"]);
    }
}

templates/tarea/_delete_form.html.twig
<form method="post" action="{{ path('tarea_delete', {'id': tarea.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tarea.id) }}">
    <button class="btn">Delete</button>
</form>

templates/tarea/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/tarea/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tarea{% endblock %}

{% block body %}
    <h1>Edit Tarea</h1>

    {{ include('tarea/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('tarea_index') }}">back to list</a>

    {{ include('tarea/_delete_form.html.twig') }}
{% endblock %}

templates/tarea/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tarea index{% endblock %}

{% block body %}
    <h1>Tarea index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Usuario_id</th>
                <th>Estado_id</th>
                <th>Titulo</th>
                <th>Description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for tarea in tareas %}
            <tr>
                <td>{{ tarea.id }}</td>
                <td>{{ tarea.usuarioId }}</td>
                <td>{{ tarea.estadoId }}</td>
                <td>{{ tarea.titulo }}</td>
                <td>{{ tarea.description }}</td>
                <td>
                    <a href="{{ path('tarea_show', {'id': tarea.id}) }}">show</a>
                    <a href="{{ path('tarea_edit', {'id': tarea.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('tarea_new') }}">Create new</a>
{% endblock %}

templates/tarea/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tarea{% endblock %}

{% block body %}
    <h1>Create new Tarea</h1>

    {{ include('tarea/_form.html.twig') }}

    <a href="{{ path('tarea_index') }}">back to list</a>
{% endblock %}

templates/tarea/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tarea{% endblock %}

{% block body %}
    <h1>Tarea</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ tarea.id }}</td>
            </tr>
            <tr>
                <th>Usuario_id</th>
                <td>{{ tarea.usuarioId }}</td>
            </tr>
            <tr>
                <th>Estado_id</th>
                <td>{{ tarea.estadoId }}</td>
            </tr>
            <tr>
                <th>Titulo</th>
                <td>{{ tarea.titulo }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ tarea.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('tarea_index') }}">back to list</a>

    <a href="{{ path('tarea_edit', {'id': tarea.id}) }}">edit</a>

    {{ include('tarea/_delete_form.html.twig') }}
{% endblock %}